print("====================")
print(" BEST FRIEND MAKER")
print("====================")
print("Hi. I'm the computer.")
name = input("What's your name?")
color = input(f"Hello, {name}! What's your favorite color?")
movie = input(f"No way! My favorite color is also {color}! What's your favorite movie?")
game = input(f"What!?! My favorite movie is also {movie}! What is your favorite game?")
print(f"Get out of here! My favorite is {game}, too! We like the same things! We should be best friends!")